server:
  port: 80

spring:
  datasource:
    name: test
    type: com.alibaba.druid.pool.DruidDataSource

    druid:
      url: jdbc:mysql://127.0.0.1:3306/kedachihuo?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CTT
      username: root
      password: 456789 # 使用druid数据源
      driver-class-name: com.mysql.cj.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      max-pool-prepared-statement-per-connection-size: 20
  thymeleaf:
    prefix: /page/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
  mvc:
    view:
      suffix: .html
      prefix: /page/
  main:
    banner-mode: "off"


mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: top.axbt.to.domain # 注意：对应实体类的路径
#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql



#  server.tomcat.uri-encoding=UTF-8
#  spring.http.encoding.charset=UTF-8
#  spring.http.encoding.enabled=true
#  spring.http.encoding.force=true
#  spring.messages.encoding=UTF-8
#wechat:
#  mpAppId: wxd898fcb01713c658
#  mpAppSecret: 29d8a650db31472aa87800e3b0d739f2
#  openAppId: wx6ad144e54af67d87
#  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
#  mchId: 1409146202
#  mchKey: c976503d34ca432c6011361f969fd8d85
#  keyPath: /var/weixin_cert/h5.p12
#  notifyUrl: http://sell.natapp4.cc/sell/pay/notify
#  templateId:
#    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ
#
#projectUrl:
#  wechatMpAuthorize: http://sell.natapp4.cc
#  wechatOpenAuthorize: http://sell.natapp4.cc
#  sell: http://sell.natapp4.cc
#spring.thymeleaf.prefix=classpath:/templates/
#spring.thymeleaf.suffix=.html
#spring.thymeleaf.mode=HTML5
#spring.thymeleaf.encoding=UTF-8
#spring.thymeleaf.content-type=text/html; charset=utf-8